############################################################

# 0. Config

@PORT={{$dotenv NEXTJS_PORT}}
@LOCAL_ADDR=http://localhost:{{PORT}}

############################################################

# 0. Misc

### 0.1. Health

GET {{LOCAL_ADDR}}/api/health

############################################################

# 1. Graph

### 1.1. Get Everything

GET {{LOCAL_ADDR}}/api/graph

############################################################

# 2. Items

### 2.1. Get Item

@ITEM_ID=1

GET {{LOCAL_ADDR}}/api/items/{{ITEM_ID}}

### 2.2. User's Items

@USER_ID=3

GET {{LOCAL_ADDR}}/api/items/users/{{USER_ID}}

### 2.3. Create Item

POST {{LOCAL_ADDR}}/api/items
Content-Type: "application/json"

{
    "user_id": 4,
    "title": "Test 1",
    "content": "This is a test item"
}

############################################################