############################################################

# 0. Config

@PORT={{$dotenv NEXTJS_PORT}}
# @PORT=3000
@LOCAL_ADDR=http://localhost:{{PORT}}

############################################################

# 0. Misc

###

GET {{LOCAL_ADDR}}/api/health

############################################################

# 1. Graph

### Get Everything

GET {{LOCAL_ADDR}}/api/graph

############################################################