############################################################

# 0.1. Config

@PORT={{$dotenv NEXTJS_PORT}}
@LOCAL_ADDR=http://localhost:{{PORT}}
@API_URL={{LOCAL_ADDR}}/api

############################################################

# 0.2. Misc

### 0.2.1. Health

GET {{API_URL}}/health

### 0.2.2. Reset DB

POST {{API_URL}}/reset

############################################################

# 1. Graph

### 1.1. Get Everything

GET {{API_URL}}/graph

############################################################

# 2. Items

### 2.1. Get Item

@ITEM_ID=1

GET {{API_URL}}/items/{{ITEM_ID}}

### 2.2. User's Items

@USER_ID=3

GET {{API_URL}}/items/users/{{USER_ID}}

### 2.3. Create Item

POST {{API_URL}}/items
Content-Type: "application/json"
user_id: 0

{
    "title": "Test 1",
    "content": "This is a test item"
}

### 2.4. Connect Items

@CONNECTED_ITEM_ID=20
@CONNECTEE_ITEM_ID=21

POST {{API_URL}}/items/{{CONNECTED_ITEM_ID}}/connections/{{CONNECTEE_ITEM_ID}}
Content-Type: "application/json"
user_id: 4

{
    "title": "Test Connection"
}

### 2.5. Get Item Votes

@GET_VOTES_ITEM_ID=20

GET {{API_URL}}/items/{{GET_VOTES_ITEM_ID}}/votes

### 2.6. Post Item Vote

@POST_VOTE_ITEM_OR_CONNECTION_ID=2

POST {{API_URL}}/items/{{POST_VOTE_ITEM_OR_CONNECTION_ID}}/votes
user_id: 3
Content-Type: "application/json"

{
    "points": 7
}

### 2.7. Post Comment

@POST_COMMENT_ITEM=44

POST {{API_URL}}/items/{{POST_COMMENT_ITEM}}/comments
user_id: 43
Content-Type: "application/json"

{
    "content": "Test Comment 2"
}

### 2.8. Get Item's Comments

GET {{API_URL}}/items/{{POST_COMMENT_ITEM}}/comments

############################################################

# 3. Users

### 3.1. Get All Users

GET {{API_URL}}/users

### 3.2. Get User

@GET_USER_ID=3

GET {{API_URL}}/users/{{GET_USER_ID}}

### 3.3. Create User

POST {{API_URL}}/users
Content-Type: "application/json"

{
    "name": "Test User",
    "email": "test@user.com"
}

### 3.4. Get User Follows

@GET_FOLLOWS_USER_ID=3

GET {{API_URL}}/users/{{GET_FOLLOWS_USER_ID}}/follows

### 3.5. Create Follow

@FOLLOWED_USER_ID=1
@FOLLOWER_USER_ID=2

POST {{API_URL}}/users/{{FOLLOWED_USER_ID}}/follows
user_id: {{FOLLOWER_USER_ID}}

############################################################